### ISSUE TITLE
Sell Equipment Text Fields Management Issues(v0.1_Test_Case_No.=XS6B)

### ISSUE THREAD

**Issue by KaustavSaha10** [KaustavSaha10/Xsociety#9]
On User click, text fields' default values not clearing out leaving the user to delete the string first before entering their data.
Input Validation lacking in URL/Link field and Equipment name field.

**Comment by maitri2000** [comment]
Working on it.

**Comment by maitri2000** [comment]
Issue patched

**Comment by KaustavSaha10** [comment]
Nice work
